language: node_js
node_js: 0.11
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
  - git config --global user.name "Travis CI"
  - git config --global user.email "fabio@elizandro.com.br"
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/report-lcov/lcov.info
  - gem install heroku
  - heroku keys:clear
  - yes | heroku keys:add
  - sh travis-deploy.sh
services: mongodb
addons:
  code_climate:
    repo_token: e4ac77f28625f3e0edb1f44aae17436f2a33c2834ae270b56c103f1183c63642
